---
  extends: eslint
  env:
    node: true
    es6: true
    mocha: true
  rules:
    strict:
      - error
      - never
    quotes:
      - error
      - single
    indent:
      - error
      - 2
    comma-dangle: 'off'
    require-jsdoc: 'off'
    no-process-exit: 'off'
    no-console: 'off'
    consistent-return: 'off'
    no-confusing-arrow: 'off'
  globals:
    expect: true
