---
  extends: eslint
  env:
    node: true
    es6: true
    mocha: true
  rules:
    semi:
      - error
      - never
    strict:
      - error
      - never
    quotes:
      - error
      - single
    indent:
      - error
      - 2
    require-jsdoc: 'off'
    brace-style:
      - error
      - stroustrup
  globals:
    mockery: true
    sinon: true
    expect: true
